/**
 * exportRoadmap.js — Export utilities using html2pdf.js for PDF and Blob for Markdown
 */

const INTERESTS_LABEL = {
  frontend: 'Frontend Development', cybersecurity: 'Cybersecurity',
  cloud: 'Cloud Computing',         uiux: 'UI/UX Design',
  aiml: 'AI / Machine Learning',    data: 'Data Science',
  backend: 'Backend Development',   devops: 'DevOps & SRE',
};

export function roadmapToMarkdown(roadmap, preferences) {
  const interestLabel = INTERESTS_LABEL[preferences?.interest] || preferences?.interest || 'Technology';
  const level = preferences?.skillLevel
    ? preferences.skillLevel.charAt(0).toUpperCase() + preferences.skillLevel.slice(1) : '';
  const completed = roadmap.modules.filter(m => m.completed).length;
  const total = roadmap.modules.length;
  const pct = total > 0 ? Math.round((completed / total) * 100) : 0;

  const lines = [
    `# ${roadmap.title}`,
    ``,
    `> Generated by LearnMate AI · Granite 3.0 Engine`,
    ``,
    `## Summary`,
    ``,
    roadmap.summary || '',
    ``,
    `**Career Outcome:** ${roadmap.careerOutcome || 'N/A'}  `,
    `**Total Duration:** ${roadmap.totalWeeks} weeks  `,
    `**Progress:** ${completed}/${total} modules (${pct}%)  `,
    `**Track:** ${interestLabel} · ${level}`,
    ``,
    `---`,
    ``,
    `## Learning Modules`,
    ``,
  ];

  roadmap.modules.forEach((m, i) => {
    const status = m.completed ? '✅' : '⬜';
    lines.push(`### ${status} Module ${i + 1}: ${m.title}`);
    lines.push(``);
    lines.push(`**Difficulty:** ${m.difficulty} · **Duration:** ${m.weeks} week(s)`);
    lines.push(``);
    lines.push(m.description || '');
    lines.push(``);
    if (m.topics?.length) { lines.push(`**Topics:** ${m.topics.join(', ')}`); lines.push(``); }
    if (m.ibmCourse) {
      lines.push(`**Course:** [${m.ibmCourse.name}](${m.ibmCourse.url || '#'}) _(${m.ibmCourse.duration})_`);
      lines.push(``);
    }
    if (m.milestoneProject) { lines.push(`**Milestone:** ${m.milestoneProject}`); lines.push(``); }
    lines.push(`---`); lines.push(``);
  });

  lines.push(`_Exported from LearnMate on ${new Date().toLocaleDateString()}_`);
  return lines.join('\n');
}

export function downloadFile(content, filename, mimeType) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename;
  document.body.appendChild(a); a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function exportMarkdown(roadmap, preferences) {
  const md = roadmapToMarkdown(roadmap, preferences);
  const slug = (roadmap.title || 'roadmap').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
  downloadFile(md, `${slug}.md`, 'text/markdown;charset=utf-8');
}

/**
 * Export roadmap as a styled PDF using html2pdf.js
 */
export async function exportPDF(roadmap, preferences, userName) {
  const html2pdf = (await import('html2pdf.js')).default;

  const interestLabel = INTERESTS_LABEL[preferences?.interest] || preferences?.interest || '';
  const level = preferences?.skillLevel || '';
  const completed = roadmap.modules.filter(m => m.completed).length;
  const pct = roadmap.modules.length > 0 ? Math.round((completed / roadmap.modules.length) * 100) : 0;

  const modulesHTML = roadmap.modules.map((m, i) => `
    <div class="module ${m.completed ? 'done' : ''}">
      <div class="mod-header">
        <div class="mod-num">${m.completed ? '✓' : i + 1}</div>
        <div>
          <div class="mod-title">${m.title}</div>
          <div class="mod-meta">
            <span class="badge">${m.difficulty}</span>
            <span class="badge">${m.weeks} week(s)</span>
            ${m.completed ? '<span class="badge green">✓ Completed</span>' : ''}
          </div>
        </div>
      </div>
      <div class="mod-desc">${m.description || ''}</div>
      ${m.topics?.length ? `<div class="mod-topics"><strong>Topics:</strong> ${m.topics.join(', ')}</div>` : ''}
      ${m.ibmCourse ? `<div class="mod-course">📚 <strong>Course:</strong> ${m.ibmCourse.name} (${m.ibmCourse.duration})</div>` : ''}
      ${m.milestoneProject ? `<div class="mod-milestone">🏆 <strong>Milestone:</strong> ${m.milestoneProject}</div>` : ''}
    </div>
  `).join('');

  const container = document.createElement('div');
  container.innerHTML = `
    <style>
      * { box-sizing: border-box; margin: 0; padding: 0; }
      body, div { font-family: 'Segoe UI', Arial, sans-serif; font-size: 13px; color: #1e293b; }
      .page { padding: 40px; max-width: 740px; }
      .header { display: flex; align-items: flex-start; justify-content: space-between; margin-bottom: 24px; padding-bottom: 16px; border-bottom: 3px solid #6366f1; }
      .brand { font-size: 10px; font-weight: 700; letter-spacing: 2px; text-transform: uppercase; color: #6366f1; margin-bottom: 6px; }
      .title { font-size: 22px; font-weight: 900; color: #0f172a; margin-bottom: 6px; }
      .meta { font-size: 12px; color: #64748b; }
      .prog-wrap { width: 160px; text-align: right; }
      .prog-label { font-size: 28px; font-weight: 900; color: #6366f1; }
      .prog-sub { font-size: 11px; color: #94a3b8; }
      .prog-bar { height: 6px; background: #f1f5f9; border-radius: 99px; margin-top: 6px; }
      .prog-fill { height: 6px; border-radius: 99px; background: linear-gradient(90deg,#6366f1,#34d399); }
      .summary { background: #f8faff; border-left: 4px solid #6366f1; padding: 12px 16px; margin-bottom: 20px; border-radius: 0 8px 8px 0; font-size: 13px; line-height: 1.6; color: #334155; }
      .outcome { font-size: 12px; color: #059669; font-weight: 600; margin-bottom: 20px; }
      .section-title { font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 1.5px; color: #6366f1; margin-bottom: 12px; }
      .module { border: 1px solid #e2e8f0; border-radius: 8px; padding: 14px; margin-bottom: 12px; page-break-inside: avoid; }
      .module.done { border-color: #86efac; background: #f0fdf4; }
      .mod-header { display: flex; align-items: flex-start; gap: 10px; margin-bottom: 8px; }
      .mod-num { width: 26px; height: 26px; border-radius: 50%; background: #6366f1; color: white; font-size: 11px; font-weight: 700; display: flex; align-items: center; justify-content: center; flex-shrink: 0; }
      .module.done .mod-num { background: #22c55e; }
      .mod-title { font-size: 14px; font-weight: 700; color: #0f172a; margin-bottom: 4px; }
      .mod-meta { display: flex; gap: 6px; flex-wrap: wrap; }
      .badge { background: #f1f5f9; border: 1px solid #e2e8f0; border-radius: 99px; padding: 1px 7px; font-size: 10px; color: #64748b; }
      .badge.green { background: #dcfce7; border-color: #86efac; color: #166534; }
      .mod-desc { font-size: 12px; color: #475569; line-height: 1.5; margin-top: 6px; }
      .mod-topics, .mod-course { font-size: 11px; color: #64748b; margin-top: 5px; }
      .mod-milestone { margin-top: 6px; background: #fefce8; border: 1px solid #fde68a; border-radius: 4px; padding: 6px 10px; font-size: 11px; color: #92400e; }
      .footer { margin-top: 28px; padding-top: 12px; border-top: 1px solid #e2e8f0; font-size: 10px; color: #94a3b8; text-align: center; }
    </style>
    <div class="page">
      <div class="header">
        <div>
          <div class="brand">LearnMate · Granite 3.0 AI</div>
          <div class="title">${roadmap.title}</div>
          <div class="meta">${interestLabel} · ${level}${userName ? ' · ' + userName : ''}</div>
          <div class="meta">${roadmap.totalWeeks} weeks · ${completed}/${roadmap.modules.length} modules</div>
        </div>
        <div class="prog-wrap">
          <div class="prog-label">${pct}%</div>
          <div class="prog-sub">Complete</div>
          <div class="prog-bar"><div class="prog-fill" style="width:${pct}%"></div></div>
        </div>
      </div>
      <div class="summary">${roadmap.summary || ''}</div>
      ${roadmap.careerOutcome ? `<div class="outcome">🎯 Career Outcome: ${roadmap.careerOutcome}</div>` : ''}
      <div class="section-title">Learning Modules</div>
      ${modulesHTML}
      <div class="footer">Generated by LearnMate AI on ${new Date().toLocaleDateString()} · Granite 3.0 Engine</div>
    </div>
  `;

  document.body.appendChild(container);
  const slug = (roadmap.title || 'roadmap').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

  await html2pdf().set({
    margin: 0,
    filename: `${slug}.pdf`,
    image: { type: 'jpeg', quality: 0.95 },
    html2canvas: { scale: 2, useCORS: true, logging: false },
    jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
    pagebreak: { mode: ['avoid-all', 'css'] },
  }).from(container).save();

  document.body.removeChild(container);
}
